services:
  piston:
    image: ghcr.io/engineer-man/piston:latest
    ports:
      - "2000:2000"
    restart: unless-stopped
    volumes:
      - piston-data:/piston
    privileged: true
volumes:
  piston-data:
